MvcPersonajesExamen/Models/ErrorViewModel.cs
namespace MvcPersonajesExamen.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcPersonajesExamen/Models/Personaje.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace MvcPersonajesExamen.Models
{
    public class Personaje
    {
        public int IdPersonaje { get; set; }
        public string Nombre { get; set; }
        public string Imagen { get; set; }
        public string Serie { get; set; }
    }
}

MvcPersonajesExamen/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcPersonajesExamen.Models;
using System.Diagnostics;

namespace MvcPersonajesExamen.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcPersonajesExamen/Controllers/PersonajesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcPersonajesExamen.Models;
using MvcPersonajesExamen.Services;

namespace MvcPersonajesExamen.Controllers
{
    public class PersonajesController : Controller
    {
        private ServicePersonajes service;

        public PersonajesController(ServicePersonajes service)
        {
            this.service = service;
        }
    
        public async Task<IActionResult> Index()
        {
            List<Personaje> personajes = await 
                this.service.GetPersonajesAsync();
            return View(personajes);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Personaje personaje)
        {
            await this.service.CrearPersonajeAsync
                (personaje.IdPersonaje, personaje.Nombre,
                personaje.Imagen, personaje.Serie);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            Personaje personaje = await this.service.FindPersonajeAsync(id);
            return View(personaje);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Personaje personaje)
        {
            await this.service.EditarPersonajeAsync
                (personaje.IdPersonaje, personaje.Nombre,
                personaje.Imagen, personaje.Serie);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Buscador()
        {
            List<string> series = await this.service.GetSeriesAsync();
            ViewData["SERIES"] = series;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Buscador(string serie)
        {
            List<string> series = await this.service.GetSeriesAsync();
            ViewData["SERIES"] = series;
            List<Personaje> personajes = await this.service
                .GetPersonajesSerieAsync(serie);
            return View(personajes);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await this.service.DeletePersonajeAsync(id);
            return RedirectToAction("Index");
        }
    }
}

MvcPersonajesExamen/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcPersonajesExamen/Views/Personajes/Buscador.cshtml
@model List<Personaje>

@{
    ViewData["Title"] = "Buscador";
    List<string> series = ViewData["SERIES"] as List<string>;
}
<h1>Buscador</h1>

<form method="post">
    <label>Seleccione la serie:</label>
    <select name="serie" class="form-control">
        @foreach(string serie in series)
        {
            <option value="@serie">@serie</option>
        }
    </select>
    <br />
    <button class="btn btn-info">Buscar!</button>
</form>

@if(Model != null)
{
    <table class="table table-dark">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Imagen</th>
                <th>Serie</th>
            </tr>
        </thead>
        <tbody>
            @foreach(Personaje p in Model)
            {
                <tr>
                    <td>@p.IdPersonaje</td>
                    <td>@p.Nombre</td>
                    <td>
                        <img src="@p.Imagen" style="width:100px;height:100px;"/>
                    </td>
                    <td>@p.Serie</td>
                </tr>
            }
        </tbody>
    </table>
}

MvcPersonajesExamen/Views/Personajes/Create.cshtml
@model MvcPersonajesExamen.Models.Personaje

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Personaje</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdPersonaje" class="control-label"></label>
                <input asp-for="IdPersonaje" class="form-control" />
                <span asp-validation-for="IdPersonaje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Serie" class="control-label"></label>
                <input asp-for="Serie" class="form-control" />
                <span asp-validation-for="Serie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcPersonajesExamen/Views/Personajes/Edit.cshtml
@model MvcPersonajesExamen.Models.Personaje

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Personaje</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdPersonaje" class="control-label"></label>
                <input asp-for="IdPersonaje" class="form-control" />
                <span asp-validation-for="IdPersonaje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Serie" class="control-label"></label>
                <input asp-for="Serie" class="form-control" />
                <span asp-validation-for="Serie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcPersonajesExamen/Views/Personajes/Index.cshtml
@model IEnumerable<MvcPersonajesExamen.Models.Personaje>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdPersonaje)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Serie)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdPersonaje)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                    <img src="@item.Imagen" style="width:100px;height:100px;" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Serie)
            </td>
            <td>
                    @Html.ActionLink("Edit", "Edit", new {  id=item.IdPersonaje }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.IdPersonaje })

                    <button class="btn btn-danger" id="eliminar">
                        Delete
                    </button>
            </td>
        </tr>
}
    </tbody>
</table>

@*lo he tenido que dejar a medias por tiempo :(*@
@section Scripts {
    <script>
        var urlApi = "https://apiexamenazureanita.azurewebsites.net/";
        $(document).ready(function () {
            $("#eliminar").click(function () {
                
            }
                }
    </script>
    

}

MvcPersonajesExamen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcPersonajesExamen</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcPersonajesExamen.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcPersonajesExamen</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Personajes" asp-action="Index">Personajes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Personajes" asp-action="Buscador">Buscador</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcPersonajesExamen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>